name: ATmosphereConf 2025
iconImageURL: https://firebasestorage.googleapis.com/v0/b/festivl.appspot.com/o/ATCON%2007.png?alt=media&token=e7eb681a-1dec-4879-b720-31fd6098272f
startDate: 2025-03-22
endDate: 2025-03-23
location: Seattle, WA
timezone: America/Los_Angeles
stages:
  - name: Main Stage
    color: 0x6B4FBB
  - name: Stream.place Room
    color: 0x2E7D9B
  - name: Bluesky Room
    color: 0x4A9B5F
